CREATE TABLE M1 (
    K INT PRIMARY KEY,
    V VARCHAR(20)
);

CREATE TABLE S1 (
    K INT PRIMARY KEY,
    MFK INT,
    V VARCHAR(20),
    FOREIGN KEY (MFK) REFERENCES M1(K)
);

CREATE TABLE M2 (
    K1 INT,
    K2 INT,
    V VARCHAR(20),
    PRIMARY KEY (K1, K2)
);

CREATE TABLE S2 (
    K INT PRIMARY KEY,
    MFK1 INT,
    MFK2 INT,
    V VARCHAR(20),
    FOREIGN KEY (MFK1, MFK2) REFERENCES M2(K1, K2)
);

ALTER TABLE S1
ADD CONSTRAINT FK_S1_M1
FOREIGN KEY (MFK) REFERENCES M1(K)
ON DELETE CASCADE ON UPDATE NO ACTION;